using System.IO;
using System.Reflection;
using System.Text;
using System.Web;
using System.Web.Hosting;
using System.Web.UI.WebControls;
using CsvHelper;
using Sabr.Models;

namespace Sabr.Migrations
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;

    internal sealed class Configuration : DbMigrationsConfiguration<Sabr.Models.ApplicationDbContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = false;
        }
        
        protected override void Seed(Sabr.Models.ApplicationDbContext context)
        {
            context.Teams.AddOrUpdate(m => m.Id,
                new Models.Team { Id = 1, TeamName = "Atlanta Hawks", City = "Atlanta" },
                new Models.Team { Id = 2, TeamName = "Boston Celtics", City = "Boston" },
                new Models.Team { Id = 3, TeamName = "Brooklyn Nets", City = "Brooklyn" },
                new Models.Team { Id = 4, TeamName = "Charlotte Hornets", City = "Charlotte" },
                new Models.Team { Id = 5, TeamName = "Chicago Bulls", City = "Chicago" },
                new Models.Team { Id = 6, TeamName = "Cleveland Cavaliers", City = "Cleveland" },
                new Models.Team { Id = 7, TeamName = "Dallas Mavericks", City = "Dallas" },
                new Models.Team { Id = 8, TeamName = "Denver Nuggets", City = "Denver" },
                new Models.Team { Id = 9, TeamName = "Detroit Pistons", City = "Detroit" },
                new Models.Team { Id = 10, TeamName = "Golden State Warriors", City = "Oakland" },
                new Models.Team { Id = 11, TeamName = "Houston Rockets", City = "Houston" },
                new Models.Team { Id = 12, TeamName = "Indiana Pacers", City = "Indiana" },
                new Models.Team { Id = 13, TeamName = "LA Clippers", City = "Los Angeles" },
                new Models.Team { Id = 14, TeamName = "Los Angeles Lakers", City = "Los Angeles" },
                new Models.Team { Id = 15, TeamName = "Memphis Grizzlies", City = "Memphis" },
                new Models.Team { Id = 16, TeamName = "Miami Heat", City = "Miami" },
                new Models.Team { Id = 17, TeamName = "Milwaukee Bucks", City = "Milwaukee" },
                new Models.Team { Id = 18, TeamName = "Minnesota Timberwolves", City = "Minnesota" },
                new Models.Team { Id = 19, TeamName = "New Orleans Pelicans", City = "New Orleans" },
                new Models.Team { Id = 20, TeamName = "New York Knicks", City = "New York" },
                new Models.Team { Id = 21, TeamName = "Oklahoma City Thunder", City = "Oklahoma City" },
                new Models.Team { Id = 22, TeamName = "Orlando Magic", City = "Orlando" },
                new Models.Team { Id = 23, TeamName = "Philadelphia 76ers", City = "Philadelphia" },
                new Models.Team { Id = 24, TeamName = "Phoenix Suns", City = "Phoenix" },
                new Models.Team { Id = 25, TeamName = "Portland Trail Blazers", City = "Portland" },
                new Models.Team { Id = 26, TeamName = "Sacramento Kings", City = "Sacramento" },
                new Models.Team { Id = 27, TeamName = "San Antonio Spurs", City = "San Antonio" },
                new Models.Team { Id = 28, TeamName = "Toronto Raptors", City = "Toronto" },
                new Models.Team { Id = 29, TeamName = "Utah Jazz", City = "Utah" },
                new Models.Team { Id = 30, TeamName = "Washington Wizards", City = "Washington" },
                new Models.Team { Id = 31, TeamName = "Free Agency" }
            );

            context.PlayerPositions.AddOrUpdate(m => m.Id,
                new Models.PlayerPosition { Id = 1, Position = "Point Guard" },
                new Models.PlayerPosition { Id = 2, Position = "Shooting Guard" },
                new Models.PlayerPosition { Id = 3, Position = "Small Forward" },
                new Models.PlayerPosition { Id = 4, Position = "Power Forward" },
                new Models.PlayerPosition { Id = 5, Position = "Center" }
            );

            context.Seasons.AddOrUpdate(m => m.Id,
                new Models.Season { Id = 1, Year = "2015-2016" },
                new Models.Season { Id = 2, Year = "2014-2015" },
                new Models.Season { Id = 3, Year = "2013-2014" },
                new Models.Season { Id = 4, Year = "2012-2013" },
                new Models.Season { Id = 5, Year = "2011-2012" },
                new Models.Season { Id = 6, Year = "2010-2011" }
                );

            context.HistoricalTeams.AddOrUpdate(m => m.Id,
                new Models.HistoricalTeam { Id = 1, TeamName = "Cleveland Cavaliers", SeasonId = 1 },
                new Models.HistoricalTeam { Id = 2, TeamName = "Golden State Warriors", SeasonId = 2 },
                new Models.HistoricalTeam { Id = 3, TeamName = "San Antonio Spurs", SeasonId = 3 },
                new Models.HistoricalTeam { Id = 4, TeamName = "Miami Heat", SeasonId = 4 },
                new Models.HistoricalTeam { Id = 5, TeamName = "Miami Heat", SeasonId = 5 },
                new Models.HistoricalTeam { Id = 6, TeamName = "Dallas Mavericks", SeasonId = 6 }
                );

            context.Players.AddOrUpdate(m => m.Id,
                new Models.Player { Id = 1, FirstName = "Kent", LastName = "Bazemore", FootHeight = 6, InchHeight = 5, Weight = 201, Age = 27, PlayerPositionId = 3, TeamId = 1 },
                new Models.Player { Id = 2, FirstName = "DeAndre'", LastName = "Bembry", FootHeight = 6, InchHeight = 6, Weight = 210, Age = 22, PlayerPositionId = 3, TeamId = 1 },
                new Models.Player { Id = 3, FirstName = "Malcolm", LastName = "Delaney", FootHeight = 6, InchHeight = 3, Weight = 190, Age = 27, PlayerPositionId = 1, TeamId = 1 },
                new Models.Player { Id = 4, FirstName = "Mike", LastName = "Dunleavy", FootHeight = 6, InchHeight = 9, Weight = 230, Age = 36, PlayerPositionId = 2, TeamId = 1 },
                new Models.Player { Id = 5, FirstName = "Tim", LastName = "Hardaway", FootHeight = 6, InchHeight = 6, Weight = 205, Age = 24, PlayerPositionId = 2, TeamId = 1 },
                new Models.Player { Id = 6, FirstName = "Dwight", LastName = "Howard", FootHeight = 6, InchHeight = 11, Weight = 265, Age = 31, PlayerPositionId = 5, TeamId = 1 },
                new Models.Player { Id = 7, FirstName = "Kris", LastName = "Humphries", FootHeight = 6, InchHeight = 9, Weight = 235, Age = 32, PlayerPositionId = 4, TeamId = 1 },
                new Models.Player { Id = 8, FirstName = "Ersan", LastName = "Ilyasova", FootHeight = 6, InchHeight = 10, Weight = 235, Age = 29, PlayerPositionId = 4, TeamId = 1 },
                new Models.Player { Id = 9, FirstName = "Ryan", LastName = "Kelly", FootHeight = 6, InchHeight = 11, Weight = 230, Age = 25, PlayerPositionId = 4, TeamId = 1 },
                new Models.Player { Id = 10, FirstName = "Paul", LastName = "Millsap", FootHeight = 6, InchHeight = 8, Weight = 246, Age = 32, PlayerPositionId = 4, TeamId = 1 },
                new Models.Player { Id = 11, FirstName = "Mike", LastName = "Muscala", FootHeight = 6, InchHeight = 11, Weight = 240, Age = 25, PlayerPositionId = 4, TeamId = 1 },
                new Models.Player { Id = 12, FirstName = "Taurean", LastName = "Waller-Prince", FootHeight = 6, InchHeight = 8, Weight = 220, Age = 22, PlayerPositionId = 3, TeamId = 1 },
                new Models.Player { Id = 13, FirstName = "Dennis", LastName = "Schroder", FootHeight = 6, InchHeight = 1, Weight = 172, Age = 23, PlayerPositionId = 1, TeamId = 1 },
                new Models.Player { Id = 14, FirstName = "Thabo", LastName = "Sefolosha", FootHeight = 6, InchHeight = 7, Weight = 220, Age = 32, PlayerPositionId = 3, TeamId = 1 },
                new Models.Player { Id = 15, FirstName = "Giannis", LastName = "Antetokounmpo", FootHeight = 6, InchHeight = 11, Weight = 222, Age = 22, PlayerPositionId = 3, TeamId = 17 },
                new Models.Player { Id = 16, FirstName = "Michael", LastName = "Beasley", FootHeight = 6, InchHeight = 10, Weight = 235, Age = 28, PlayerPositionId = 3, TeamId = 17 },
                new Models.Player { Id = 17, FirstName = "Malcolm", LastName = "Brogdon", FootHeight = 6, InchHeight = 5, Weight = 215, Age = 24, PlayerPositionId = 2, TeamId = 17 },
                new Models.Player { Id = 18, FirstName = "Matthew", LastName = "Dellavedova", FootHeight = 6, InchHeight = 4, Weight = 198, Age = 26, PlayerPositionId = 1, TeamId = 17 },
                new Models.Player { Id = 19, FirstName = "Spencer", LastName = "Hawes", FootHeight = 7, InchHeight = 1, Weight = 245, Age = 28, PlayerPositionId = 4, TeamId = 17 },
                new Models.Player { Id = 20, FirstName = "John", LastName = "Henson", FootHeight = 6, InchHeight = 11, Weight = 229, Age = 26, PlayerPositionId = 5, TeamId = 17 },
                new Models.Player { Id = 21, FirstName = "Thon", LastName = "Maker", FootHeight = 7, InchHeight = 1, Weight = 223, Age = 20, PlayerPositionId = 4, TeamId = 17 },
                new Models.Player { Id = 22, FirstName = "Khris", LastName = "Middleton", FootHeight = 6, InchHeight = 8, Weight = 234, Age = 25, PlayerPositionId = 2, TeamId = 17 },
                new Models.Player { Id = 23, FirstName = "Greg", LastName = "Monroe", FootHeight = 6, InchHeight = 11, Weight = 265, Age = 26, PlayerPositionId = 5, TeamId = 17 },
                new Models.Player { Id = 24, FirstName = "Jabari", LastName = "Parker", FootHeight = 6, InchHeight = 8, Weight = 250, Age = 21, PlayerPositionId = 4, TeamId = 17 },
                new Models.Player { Id = 25, FirstName = "Gary", LastName = "Payton", FootHeight = 6, InchHeight = 3, Weight = 190, Age = 24, PlayerPositionId = 1, TeamId = 17 },
                new Models.Player { Id = 26, FirstName = "Tony", LastName = "Snell", FootHeight = 6, InchHeight = 7, Weight = 217, Age = 25, PlayerPositionId = 2, TeamId = 17 },
                new Models.Player { Id = 27, FirstName = "Mirza", LastName = "Teletovic", FootHeight = 6, InchHeight = 9, Weight = 245, Age = 31, PlayerPositionId = 4, TeamId = 17 },
                new Models.Player { Id = 28, FirstName = "Jason", LastName = "Terry", FootHeight = 6, InchHeight = 2, Weight = 185, Age = 39, PlayerPositionId = 2, TeamId = 17 },
                new Models.Player { Id = 29, FirstName = "Rashad", LastName = "Vaughn", FootHeight = 6, InchHeight = 6, Weight = 202, Age = 20, PlayerPositionId = 2, TeamId = 17 },
                new Models.Player { Id = 30, FirstName = "Jimmy", LastName = "Butler", FootHeight = 6, InchHeight = 7, Weight = 231, Age = 27, PlayerPositionId = 3, TeamId = 5 },
                new Models.Player { Id = 31, FirstName = "Isaiah", LastName = "Canaan", FootHeight = 6, InchHeight = 0, Weight = 201, Age = 25, PlayerPositionId = 1, TeamId = 5 },
                new Models.Player { Id = 32, FirstName = "Michael", LastName = "Carter-Williams", FootHeight = 6, InchHeight = 6, Weight = 190, Age = 25, PlayerPositionId = 1, TeamId = 5 },
                new Models.Player { Id = 33, FirstName = "Cristiano", LastName = "Felicio", FootHeight = 6, InchHeight = 9, Weight = 266, Age = 24, PlayerPositionId = 4, TeamId = 5 },
                new Models.Player { Id = 34, FirstName = "Jerian", LastName = "Grant", FootHeight = 6, InchHeight = 4, Weight = 198, Age = 24, PlayerPositionId = 1, TeamId = 5 },
                new Models.Player { Id = 35, FirstName = "Joffrey", LastName = "Lauvergne", FootHeight = 6, InchHeight = 11, Weight = 220, Age = 25, PlayerPositionId = 5, TeamId = 5 },
                new Models.Player { Id = 36, FirstName = "Robin", LastName = "Lopez", FootHeight = 7, InchHeight = 0, Weight = 255, Age = 28, PlayerPositionId = 5, TeamId = 5 },
                new Models.Player { Id = 37, FirstName = "Nikola", LastName = "Mirotic", FootHeight = 6, InchHeight = 10, Weight = 238, Age = 26, PlayerPositionId = 4, TeamId = 5 },
                new Models.Player { Id = 38, FirstName = "Anthony", LastName = "Morrow", FootHeight = 6, InchHeight = 5, Weight = 210, Age = 31, PlayerPositionId = 2, TeamId = 5 },
                new Models.Player { Id = 39, FirstName = "Cameron", LastName = "Payne", FootHeight = 6, InchHeight = 3, Weight = 185, Age = 22, PlayerPositionId = 1, TeamId = 5 },
                new Models.Player { Id = 40, FirstName = "Bobby", LastName = "Portis", FootHeight = 6, InchHeight = 11, Weight = 246, Age = 22, PlayerPositionId = 4, TeamId = 5 },
                new Models.Player { Id = 41, FirstName = "Rajon", LastName = "Rondo", FootHeight = 6, InchHeight = 1, Weight = 186, Age = 31, PlayerPositionId = 1, TeamId = 5 },
                new Models.Player { Id = 42, FirstName = "Denzel", LastName = "Valentine", FootHeight = 6, InchHeight = 6, Weight = 212, Age = 23, PlayerPositionId = 2, TeamId = 5 },
                new Models.Player { Id = 43, FirstName = "Dwyane", LastName = "Wade", FootHeight = 6, InchHeight = 4, Weight = 220, Age = 35, PlayerPositionId = 2, TeamId = 5 },
                new Models.Player { Id = 44, FirstName = "Paul", LastName = "Zipser", FootHeight = 6, InchHeight = 8, Weight = 210, Age = 23, PlayerPositionId = 3, TeamId = 5 },
                new Models.Player { Id = 45, FirstName = "Andrew", LastName = "Bogut", FootHeight = 7, InchHeight = 0, Weight = 255, Age = 32, PlayerPositionId = 5, TeamId = 6 },
                new Models.Player { Id = 46, FirstName = "Kay", LastName = "Felder", FootHeight = 5, InchHeight = 9, Weight = 176, Age = 21, PlayerPositionId = 1, TeamId = 6 },
                new Models.Player { Id = 47, FirstName = "Channing", LastName = "Frye", FootHeight = 6, InchHeight = 11, Weight = 255, Age = 33, PlayerPositionId = 4, TeamId = 6 },
                new Models.Player { Id = 48, FirstName = "Kyrie", LastName = "Irving", FootHeight = 6, InchHeight = 3, Weight = 193, Age = 24, PlayerPositionId = 1, TeamId = 6 },
                new Models.Player { Id = 49, FirstName = "LeBron", LastName = "James", FootHeight = 6, InchHeight = 8, Weight = 250, Age = 32, PlayerPositionId = 3, TeamId = 6 },
                new Models.Player { Id = 50, FirstName = "Richard", LastName = "Jefferson", FootHeight = 6, InchHeight = 7, Weight = 233, Age = 36, PlayerPositionId = 3, TeamId = 6 },
                new Models.Player { Id = 51, FirstName = "James", LastName = "Jones", FootHeight = 6, InchHeight = 8, Weight = 218, Age = 36, PlayerPositionId = 2, TeamId = 6 },
                new Models.Player { Id = 52, FirstName = "Kyle", LastName = "Korver", FootHeight = 6, InchHeight = 7, Weight = 212, Age = 35, PlayerPositionId = 2, TeamId = 6 },
                new Models.Player { Id = 53, FirstName = "DeAndre", LastName = "Liggins", FootHeight = 6, InchHeight = 6, Weight = 209, Age = 28, PlayerPositionId = 2, TeamId = 6 },
                new Models.Player { Id = 54, FirstName = "Kevin", LastName = "Love", FootHeight = 6, InchHeight = 10, Weight = 251, Age = 28, PlayerPositionId = 4, TeamId = 6 },
                new Models.Player { Id = 55, FirstName = "Iman", LastName = "Shumpert", FootHeight = 6, InchHeight = 5, Weight = 220, Age = 26, PlayerPositionId = 2, TeamId = 6 },
                new Models.Player { Id = 56, FirstName = "J.R.", LastName = "Smith", FootHeight = 6, InchHeight = 6, Weight = 225, Age = 31, PlayerPositionId = 2, TeamId = 6 },
                new Models.Player { Id = 57, FirstName = "Tristan", LastName = "Thompson", FootHeight = 6, InchHeight = 9, Weight = 238, Age = 25, PlayerPositionId = 5, TeamId = 6 },
                new Models.Player { Id = 58, FirstName = "Deron", LastName = "Williams", FootHeight = 6, InchHeight = 3, Weight = 200, Age = 32, PlayerPositionId = 1, TeamId = 6 },
                new Models.Player { Id = 59, FirstName = "Derrick", LastName = "Williams", FootHeight = 6, InchHeight = 8, Weight = 240, Age = 25, PlayerPositionId = 4, TeamId = 6 },
                new Models.Player { Id = 60, FirstName = "Aron", LastName = "Baynes", FootHeight = 6, InchHeight = 10, Weight = 260, Age = 30, PlayerPositionId = 5, TeamId = 9 },
                new Models.Player { Id = 61, FirstName = "Reggie", LastName = "Bullock", FootHeight = 6, InchHeight = 7, Weight = 205, Age = 25, PlayerPositionId = 3, TeamId = 9 },
                new Models.Player { Id = 62, FirstName = "Kentavious", LastName = "Caldwell-Pope", FootHeight = 6, InchHeight = 5, Weight = 205, Age = 24, PlayerPositionId = 2, TeamId = 9 },
                new Models.Player { Id = 63, FirstName = "Andre", LastName = "Drummond", FootHeight = 6, InchHeight = 11, Weight = 279, Age = 23, PlayerPositionId = 5, TeamId = 9 },
                new Models.Player { Id = 64, FirstName = "Henry", LastName = "Ellenson", FootHeight = 6, InchHeight = 11, Weight = 245, Age = 20, PlayerPositionId = 4, TeamId = 9 },
                new Models.Player { Id = 65, FirstName = "Michael", LastName = "Gbinije", FootHeight = 6, InchHeight = 7, Weight = 200, Age = 24, PlayerPositionId = 2, TeamId = 9 },
                new Models.Player { Id = 66, FirstName = "Tobias", LastName = "Harris", FootHeight = 6, InchHeight = 9, Weight = 235, Age = 24, PlayerPositionId = 3, TeamId = 9 },
                new Models.Player { Id = 67, FirstName = "Darrun", LastName = "Hilliard", FootHeight = 6, InchHeight = 6, Weight = 205, Age = 23, PlayerPositionId = 2, TeamId = 9 },
                new Models.Player { Id = 68, FirstName = "Reggie", LastName = "Jackson", FootHeight = 6, InchHeight = 3, Weight = 208, Age = 26, PlayerPositionId = 1, TeamId = 9 },
                new Models.Player { Id = 69, FirstName = "Stanley", LastName = "Johnson", FootHeight = 6, InchHeight = 7, Weight = 245, Age = 20, PlayerPositionId = 3, TeamId = 9 },
                new Models.Player { Id = 70, FirstName = "Jon", LastName = "Leuer", FootHeight = 6, InchHeight = 10, Weight = 228, Age = 27, PlayerPositionId = 4, TeamId = 9 },
                new Models.Player { Id = 71, FirstName = "Boban", LastName = "Marjanovic", FootHeight = 7, InchHeight = 3, Weight = 290, Age = 28, PlayerPositionId = 5, TeamId = 9 },
                new Models.Player { Id = 72, FirstName = "Marcus", LastName = "Morris", FootHeight = 6, InchHeight = 9, Weight = 235, Age = 27, PlayerPositionId = 4, TeamId = 9 },
                new Models.Player { Id = 73, FirstName = "Ish", LastName = "Smith", FootHeight = 6, InchHeight = 0, Weight = 175, Age = 28, PlayerPositionId = 1, TeamId = 9 },
                new Models.Player { Id = 74, FirstName = "Beno", LastName = "Udrih", FootHeight = 6, InchHeight = 3, Weight = 205, Age = 34, PlayerPositionId = 1, TeamId = 9 },
                new Models.Player { Id = 75, FirstName = "Lavoy", LastName = "Allen", FootHeight = 6, InchHeight = 9, Weight = 260, Age = 28, PlayerPositionId = 4, TeamId = 12 },
                new Models.Player { Id = 76, FirstName = "Aaron", LastName = "Brooks", FootHeight = 6, InchHeight = 0, Weight = 161, Age = 32, PlayerPositionId = 1, TeamId = 12 },
                new Models.Player { Id = 77, FirstName = "Rakeem", LastName = "Christmas", FootHeight = 6, InchHeight = 9, Weight = 250, Age = 25, PlayerPositionId = 4, TeamId = 12 },
                new Models.Player { Id = 78, FirstName = "Monta", LastName = "Ellis", FootHeight = 6, InchHeight = 3, Weight = 185, Age = 31, PlayerPositionId = 2, TeamId = 12 },
                new Models.Player { Id = 79, FirstName = "Paul", LastName = "George", FootHeight = 6, InchHeight = 9, Weight = 220, Age = 26, PlayerPositionId = 3, TeamId = 12 },
                new Models.Player { Id = 80, FirstName = "Al", LastName = "Jefferson", FootHeight = 6, InchHeight = 10, Weight = 289, Age = 32, PlayerPositionId = 5, TeamId = 12 },
                new Models.Player { Id = 81, FirstName = "C.J.", LastName = "Miles", FootHeight = 6, InchHeight = 6, Weight = 225, Age = 29, PlayerPositionId = 3, TeamId = 12 },
                new Models.Player { Id = 82, FirstName = "Georges", LastName = "Niang", FootHeight = 6, InchHeight = 8, Weight = 230, Age = 23, PlayerPositionId = 3, TeamId = 12 },
                new Models.Player { Id = 83, FirstName = "Glenn", LastName = "Robinson", FootHeight = 6, InchHeight = 6, Weight = 222, Age = 23, PlayerPositionId = 2, TeamId = 12 },
                new Models.Player { Id = 84, FirstName = "Kevin", LastName = "Seraphin", FootHeight = 6, InchHeight = 10, Weight = 278, Age = 27, PlayerPositionId = 5, TeamId = 12 },
                new Models.Player { Id = 85, FirstName = "Rodney", LastName = "Stuckey", FootHeight = 6, InchHeight = 5, Weight = 205, Age = 30, PlayerPositionId = 1, TeamId = 12 },
                new Models.Player { Id = 86, FirstName = "Jeff", LastName = "Teague", FootHeight = 6, InchHeight = 2, Weight = 186, Age = 28, PlayerPositionId = 1, TeamId = 12 },
                new Models.Player { Id = 87, FirstName = "Myles", LastName = "Turner", FootHeight = 6, InchHeight = 11, Weight = 243, Age = 20, PlayerPositionId = 5, TeamId = 12 },
                new Models.Player { Id = 88, FirstName = "Joe", LastName = "Young", FootHeight = 6, InchHeight = 2, Weight = 180, Age = 24, PlayerPositionId = 1, TeamId = 12 },
                new Models.Player { Id = 89, FirstName = "Thaddeus", LastName = "Young", FootHeight = 6, InchHeight = 8, Weight = 221, Age = 28, PlayerPositionId = 4, TeamId = 12 },
                new Models.Player { Id = 90, FirstName = "Matt", LastName = "Barnes", FootHeight = 6, InchHeight = 7, Weight = 226, Age = 36, PlayerPositionId = 3, TeamId = 10 },
                new Models.Player { Id = 91, FirstName = "Ian", LastName = "Clark", FootHeight = 6, InchHeight = 3, Weight = 175, Age = 25, PlayerPositionId = 2, TeamId = 10 },
                new Models.Player { Id = 92, FirstName = "Stephen", LastName = "Curry", FootHeight = 6, InchHeight = 3, Weight = 190, Age = 28, PlayerPositionId = 1, TeamId = 10 },
                new Models.Player { Id = 93, FirstName = "Kevin", LastName = "Durant", FootHeight = 6, InchHeight = 9, Weight = 240, Age = 28, PlayerPositionId = 3, TeamId = 10 },
                new Models.Player { Id = 94, FirstName = "Draymond", LastName = "Green", FootHeight = 6, InchHeight = 7, Weight = 230, Age = 26, PlayerPositionId = 4, TeamId = 10 },
                new Models.Player { Id = 95, FirstName = "Andre", LastName = "Iguodala", FootHeight = 6, InchHeight = 6, Weight = 215, Age = 33, PlayerPositionId = 3, TeamId = 10 },
                new Models.Player { Id = 96, FirstName = "Damian", LastName = "Jones", FootHeight = 7, InchHeight = 0, Weight = 245, Age = 21, PlayerPositionId = 5, TeamId = 10 },
                new Models.Player { Id = 97, FirstName = "Shaun", LastName = "Livingston", FootHeight = 6, InchHeight = 7, Weight = 192, Age = 31, PlayerPositionId = 1, TeamId = 10 },
                new Models.Player { Id = 98, FirstName = "Kevon", LastName = "Looney", FootHeight = 6, InchHeight = 9, Weight = 220, Age = 21, PlayerPositionId = 3, TeamId = 10 },
                new Models.Player { Id = 99, FirstName = "James", LastName = "Michael McAdoo", FootHeight = 6, InchHeight = 9, Weight = 240, Age = 24, PlayerPositionId = 3, TeamId = 10 },
                new Models.Player { Id = 100, FirstName = "Patrick", LastName = "McCaw", FootHeight = 6, InchHeight = 7, Weight = 185, Age = 21, PlayerPositionId = 2, TeamId = 10 },
                new Models.Player { Id = 101, FirstName = "JaVale", LastName = "McGee", FootHeight = 7, InchHeight = 0, Weight = 270, Age = 29, PlayerPositionId = 5, TeamId = 10 },
                new Models.Player { Id = 102, FirstName = "Zaza", LastName = "Pachulia", FootHeight = 6, InchHeight = 11, Weight = 275, Age = 33, PlayerPositionId = 5, TeamId = 10 },
                new Models.Player { Id = 103, FirstName = "Klay", LastName = "Thompson", FootHeight = 6, InchHeight = 7, Weight = 215, Age = 27, PlayerPositionId = 2, TeamId = 10 },
                new Models.Player { Id = 104, FirstName = "David", LastName = "West", FootHeight = 6, InchHeight = 9, Weight = 250, Age = 36, PlayerPositionId = 4, TeamId = 10 },
                new Models.Player { Id = 105, FirstName = "Avery", LastName = "Bradley", FootHeight = 6, InchHeight = 2, Weight = 180, Age = 26, PlayerPositionId = 2, TeamId = 2 },
                new Models.Player { Id = 106, FirstName = "Jaylen", LastName = "Brown", FootHeight = 6, InchHeight = 7, Weight = 225, Age = 20, PlayerPositionId = 3, TeamId = 2 },
                new Models.Player { Id = 107, FirstName = "Jae", LastName = "Crowder", FootHeight = 6, InchHeight = 6, Weight = 235, Age = 26, PlayerPositionId = 3, TeamId = 2 },
                new Models.Player { Id = 108, FirstName = "Gerald", LastName = "Green", FootHeight = 6, InchHeight = 7, Weight = 205, Age = 31, PlayerPositionId = 3, TeamId = 2 },
                new Models.Player { Id = 109, FirstName = "Al", LastName = "Horford", FootHeight = 6, InchHeight = 10, Weight = 245, Age = 30, PlayerPositionId = 5, TeamId = 2 },
                new Models.Player { Id = 110, FirstName = "Demetrius", LastName = "Jackson", FootHeight = 6, InchHeight = 1, Weight = 201, Age = 22, PlayerPositionId = 1, TeamId = 2 },
                new Models.Player { Id = 111, FirstName = "Jonas", LastName = "Jerebko", FootHeight = 6, InchHeight = 10, Weight = 231, Age = 30, PlayerPositionId = 4, TeamId = 2 },
                new Models.Player { Id = 112, FirstName = "Amir", LastName = "Johnson", FootHeight = 6, InchHeight = 9, Weight = 240, Age = 30, PlayerPositionId = 4, TeamId = 2 },
                new Models.Player { Id = 113, FirstName = "Jordan", LastName = "Mickey", FootHeight = 6, InchHeight = 8, Weight = 235, Age = 22, PlayerPositionId = 4, TeamId = 2 },
                new Models.Player { Id = 114, FirstName = "Kelly", LastName = "Olynyk", FootHeight = 7, InchHeight = 0, Weight = 238, Age = 26, PlayerPositionId = 5, TeamId = 2 },
                new Models.Player { Id = 115, FirstName = "Terry", LastName = "Rozier", FootHeight = 6, InchHeight = 2, Weight = 190, Age = 23, PlayerPositionId = 1, TeamId = 2 },
                new Models.Player { Id = 116, FirstName = "Marcus", LastName = "Smart", FootHeight = 6, InchHeight = 4, Weight = 220, Age = 23, PlayerPositionId = 1, TeamId = 2 },
                new Models.Player { Id = 117, FirstName = "Isaiah", LastName = "Thomas", FootHeight = 5, InchHeight = 9, Weight = 185, Age = 28, PlayerPositionId = 1, TeamId = 2 },
                new Models.Player { Id = 118, FirstName = "James", LastName = "Young", FootHeight = 6, InchHeight = 6, Weight = 215, Age = 21, PlayerPositionId = 2, TeamId = 2 },
                new Models.Player { Id = 119, FirstName = "Tyler", LastName = "Zeller", FootHeight = 7, InchHeight = 0, Weight = 253, Age = 27, PlayerPositionId = 5, TeamId = 2 },
                new Models.Player { Id = 120, FirstName = "Quincy", LastName = "Acy", FootHeight = 6, InchHeight = 7, Weight = 240, Age = 26, PlayerPositionId = 3, TeamId = 3 },
                new Models.Player { Id = 121, FirstName = "Trevor", LastName = "Booker", FootHeight = 6, InchHeight = 8, Weight = 228, Age = 29, PlayerPositionId = 4, TeamId = 3 },
                new Models.Player { Id = 122, FirstName = "Spencer", LastName = "Dinwiddie", FootHeight = 6, InchHeight = 6, Weight = 200, Age = 24, PlayerPositionId = 1, TeamId = 3 },
                new Models.Player { Id = 123, FirstName = "Randy", LastName = "Foye", FootHeight = 6, InchHeight = 4, Weight = 218, Age = 33, PlayerPositionId = 2, TeamId = 3 },
                new Models.Player { Id = 124, FirstName = "Archie", LastName = "Goodwin", FootHeight = 6, InchHeight = 5, Weight = 205, Age = 22, PlayerPositionId = 2, TeamId = 3 },
                new Models.Player { Id = 125, FirstName = "Justin", LastName = "Hamilton", FootHeight = 7, InchHeight = 0, Weight = 255, Age = 27, PlayerPositionId = 5, TeamId = 3 },
                new Models.Player { Id = 126, FirstName = "Joe", LastName = "Harris", FootHeight = 6, InchHeight = 6, Weight = 219, Age = 25, PlayerPositionId = 3, TeamId = 3 },
                new Models.Player { Id = 127, FirstName = "Rondae", LastName = "Hollis-Jefferson", FootHeight = 6, InchHeight = 7, Weight = 214, Age = 22, PlayerPositionId = 3, TeamId = 3 },
                new Models.Player { Id = 128, FirstName = "Sean", LastName = "Kilpatrick", FootHeight = 6, InchHeight = 4, Weight = 219, Age = 27, PlayerPositionId = 2, TeamId = 3 },
                new Models.Player { Id = 129, FirstName = "Caris", LastName = "LeVert", FootHeight = 6, InchHeight = 7, Weight = 203, Age = 22, PlayerPositionId = 2, TeamId = 3 },
                new Models.Player { Id = 130, FirstName = "Jeremy", LastName = "Lin", FootHeight = 6, InchHeight = 3, Weight = 200, Age = 28, PlayerPositionId = 1, TeamId = 3 },
                new Models.Player { Id = 131, FirstName = "Brook", LastName = "Lopez", FootHeight = 7, InchHeight = 0, Weight = 268, Age = 29, PlayerPositionId = 5, TeamId = 3 },
                new Models.Player { Id = 132, FirstName = "K.J.", LastName = "McDaniels", FootHeight = 6, InchHeight = 6, Weight = 205, Age = 24, PlayerPositionId = 2, TeamId = 3 },
                new Models.Player { Id = 133, FirstName = "Andrew", LastName = "Nicholson", FootHeight = 6, InchHeight = 9, Weight = 250, Age = 27, PlayerPositionId = 4, TeamId = 3 },
                new Models.Player { Id = 134, FirstName = "Isaiah", LastName = "Whitehead", FootHeight = 6, InchHeight = 4, Weight = 213, Age = 22, PlayerPositionId = 1, TeamId = 3 },
                new Models.Player { Id = 135, FirstName = "Carmelo", LastName = "Anthony", FootHeight = 6, InchHeight = 8, Weight = 240, Age = 32, PlayerPositionId = 3, TeamId = 20 },
                new Models.Player { Id = 136, FirstName = "Ron", LastName = "Baker", FootHeight = 6, InchHeight = 4, Weight = 220, Age = 24, PlayerPositionId = 2, TeamId = 20 },
                new Models.Player { Id = 137, FirstName = "Willy", LastName = "Hernangomez", FootHeight = 6, InchHeight = 11, Weight = 240, Age = 22, PlayerPositionId = 5, TeamId = 20 },
                new Models.Player { Id = 138, FirstName = "Justin", LastName = "Holiday", FootHeight = 6, InchHeight = 6, Weight = 185, Age = 28, PlayerPositionId = 2, TeamId = 20 },
                new Models.Player { Id = 139, FirstName = "Mindaugas", LastName = "Kuzminskas", FootHeight = 6, InchHeight = 9, Weight = 215, Age = 27, PlayerPositionId = 3, TeamId = 20 },
                new Models.Player { Id = 140, FirstName = "Courtney", LastName = "Lee", FootHeight = 6, InchHeight = 5, Weight = 200, Age = 31, PlayerPositionId = 2, TeamId = 20 },
                new Models.Player { Id = 141, FirstName = "Maurice", LastName = "Ndour", FootHeight = 6, InchHeight = 9, Weight = 200, Age = 24, PlayerPositionId = 3, TeamId = 20 },
                new Models.Player { Id = 142, FirstName = "Joakim", LastName = "Noah", FootHeight = 6, InchHeight = 11, Weight = 230, Age = 32, PlayerPositionId = 5, TeamId = 20 },
                new Models.Player { Id = 143, FirstName = "Kyle", LastName = "O'Quinn", FootHeight = 6, InchHeight = 10, Weight = 250, Age = 27, PlayerPositionId = 5, TeamId = 20 },
                new Models.Player { Id = 144, FirstName = "Marshall", LastName = "Plumlee", FootHeight = 7, InchHeight = 0, Weight = 250, Age = 24, PlayerPositionId = 5, TeamId = 20 },
                new Models.Player { Id = 145, FirstName = "Kristaps", LastName = "Porzingis", FootHeight = 7, InchHeight = 3, Weight = 240, Age = 21, PlayerPositionId = 4, TeamId = 20 },
                new Models.Player { Id = 146, FirstName = "Chasson", LastName = "Randle", FootHeight = 6, InchHeight = 2, Weight = 185, Age = 24, PlayerPositionId = 1, TeamId = 20 },
                new Models.Player { Id = 147, FirstName = "Derrick", LastName = "Rose", FootHeight = 6, InchHeight = 3, Weight = 190, Age = 28, PlayerPositionId = 1, TeamId = 20 },
                new Models.Player { Id = 148, FirstName = "Lance", LastName = "Thomas", FootHeight = 6, InchHeight = 8, Weight = 235, Age = 29, PlayerPositionId = 3, TeamId = 20 },
                new Models.Player { Id = 149, FirstName = "Sasha", LastName = "Vujacic", FootHeight = 6, InchHeight = 7, Weight = 195, Age = 33, PlayerPositionId = 2, TeamId = 20 },
                new Models.Player { Id = 150, FirstName = "Justin", LastName = "Anderson", FootHeight = 6, InchHeight = 6, Weight = 228, Age = 23, PlayerPositionId = 2, TeamId = 23 },
                new Models.Player { Id = 151, FirstName = "Jerryd", LastName = "Bayless", FootHeight = 6, InchHeight = 3, Weight = 200, Age = 28, PlayerPositionId = 1, TeamId = 23 },
                new Models.Player { Id = 152, FirstName = "Robert", LastName = "Covington", FootHeight = 6, InchHeight = 9, Weight = 215, Age = 26, PlayerPositionId = 3, TeamId = 23 },
                new Models.Player { Id = 153, FirstName = "Joel", LastName = "Embiid", FootHeight = 7, InchHeight = 0, Weight = 250, Age = 23, PlayerPositionId = 5, TeamId = 23 },
                new Models.Player { Id = 154, FirstName = "Gerald", LastName = "Henderson", FootHeight = 6, InchHeight = 5, Weight = 215, Age = 29, PlayerPositionId = 2, TeamId = 23 },
                new Models.Player { Id = 155, FirstName = "Richaun", LastName = "Holmes", FootHeight = 6, InchHeight = 10, Weight = 245, Age = 23, PlayerPositionId = 4, TeamId = 23 },
                new Models.Player { Id = 156, FirstName = "Shawn", LastName = "Long", FootHeight = 6, InchHeight = 9, Weight = 255, Age = 24, PlayerPositionId = 4, TeamId = 23 },
                new Models.Player { Id = 157, FirstName = "Timothe", LastName = "Luwawu-Cabarrot", FootHeight = 6, InchHeight = 6, Weight = 205, Age = 22, PlayerPositionId = 2, TeamId = 23 },
                new Models.Player { Id = 158, FirstName = "T.J.", LastName = "McConnell", FootHeight = 6, InchHeight = 2, Weight = 200, Age = 25, PlayerPositionId = 1, TeamId = 23 },
                new Models.Player { Id = 159, FirstName = "Jahlil", LastName = "Okafor", FootHeight = 6, InchHeight = 11, Weight = 275, Age = 21, PlayerPositionId = 5, TeamId = 23 },
                new Models.Player { Id = 160, FirstName = "Alex", LastName = "Poythress", FootHeight = 6, InchHeight = 7, Weight = 238, Age = 23, PlayerPositionId = 3, TeamId = 23 },
                new Models.Player { Id = 161, FirstName = "Sergio", LastName = "Rodriguez", FootHeight = 6, InchHeight = 3, Weight = 176, Age = 30, PlayerPositionId = 1, TeamId = 23 },
                new Models.Player { Id = 162, FirstName = "Dario", LastName = "Saric", FootHeight = 6, InchHeight = 10, Weight = 223, Age = 23, PlayerPositionId = 4, TeamId = 23 },
                new Models.Player { Id = 163, FirstName = "Tiago", LastName = "Splitter", FootHeight = 6, InchHeight = 11, Weight = 245, Age = 32, PlayerPositionId = 5, TeamId = 23 },
                new Models.Player { Id = 164, FirstName = "Nik", LastName = "Stauskas", FootHeight = 6, InchHeight = 6, Weight = 205, Age = 23, PlayerPositionId = 2, TeamId = 23 },
                new Models.Player { Id = 165, FirstName = "Bruno", LastName = "Caboclo", FootHeight = 6, InchHeight = 9, Weight = 205, Age = 21, PlayerPositionId = 3, TeamId = 28 },
                new Models.Player { Id = 166, FirstName = "DeMarre", LastName = "Carroll", FootHeight = 6, InchHeight = 8, Weight = 212, Age = 30, PlayerPositionId = 3, TeamId = 28 },
                new Models.Player { Id = 167, FirstName = "DeMar", LastName = "DeRozan", FootHeight = 6, InchHeight = 7, Weight = 220, Age = 27, PlayerPositionId = 2, TeamId = 28 },
                new Models.Player { Id = 168, FirstName = "Serge", LastName = "Ibaka", FootHeight = 6, InchHeight = 10, Weight = 235, Age = 27, PlayerPositionId = 4, TeamId = 28 },
                new Models.Player { Id = 169, FirstName = "Cory", LastName = "Joseph", FootHeight = 6, InchHeight = 3, Weight = 190, Age = 25, PlayerPositionId = 1, TeamId = 28 },
                new Models.Player { Id = 170, FirstName = "Kyle", LastName = "Lowry", FootHeight = 6, InchHeight = 0, Weight = 205, Age = 31, PlayerPositionId = 1, TeamId = 28 },
                new Models.Player { Id = 171, FirstName = "Lucas", LastName = "Nogueira", FootHeight = 7, InchHeight = 0, Weight = 220, Age = 24, PlayerPositionId = 5, TeamId = 28 },
                new Models.Player { Id = 172, FirstName = "Patrick", LastName = "Patterson", FootHeight = 6, InchHeight = 9, Weight = 235, Age = 28, PlayerPositionId = 4, TeamId = 28 },
                new Models.Player { Id = 173, FirstName = "Jakob", LastName = "Poeltl", FootHeight = 7, InchHeight = 0, Weight = 230, Age = 21, PlayerPositionId = 5, TeamId = 28 },
                new Models.Player { Id = 174, FirstName = "Norman", LastName = "Powell", FootHeight = 6, InchHeight = 4, Weight = 215, Age = 23, PlayerPositionId = 2, TeamId = 28 },
                new Models.Player { Id = 175, FirstName = "Pascal", LastName = "Siakam", FootHeight = 6, InchHeight = 9, Weight = 230, Age = 23, PlayerPositionId = 4, TeamId = 28 },
                new Models.Player { Id = 176, FirstName = "P.J.", LastName = "Tucker", FootHeight = 6, InchHeight = 6, Weight = 245, Age = 32, PlayerPositionId = 3, TeamId = 28 },
                new Models.Player { Id = 177, FirstName = "Jonas", LastName = "Valanciunas", FootHeight = 7, InchHeight = 0, Weight = 255, Age = 25, PlayerPositionId = 5, TeamId = 28 },
                new Models.Player { Id = 178, FirstName = "Fred", LastName = "VanVleet", FootHeight = 6, InchHeight = 0, Weight = 195, Age = 23, PlayerPositionId = 1, TeamId = 28 },
                new Models.Player { Id = 179, FirstName = "Delon", LastName = "Wright", FootHeight = 6, InchHeight = 5, Weight = 190, Age = 25, PlayerPositionId = 1, TeamId = 28 },
                new Models.Player { Id = 180, FirstName = "Nicolas", LastName = "Batum", FootHeight = 6, InchHeight = 8, Weight = 200, Age = 28, PlayerPositionId = 2, TeamId = 4 },
                new Models.Player { Id = 181, FirstName = "Marco", LastName = "Belinelli", FootHeight = 6, InchHeight = 5, Weight = 210, Age = 31, PlayerPositionId = 2, TeamId = 4 },
                new Models.Player { Id = 182, FirstName = "Treveon", LastName = "Graham", FootHeight = 6, InchHeight = 6, Weight = 226, Age = 23, PlayerPositionId = 2, TeamId = 4 },
                new Models.Player { Id = 183, FirstName = "Frank", LastName = "Kaminsky", FootHeight = 7, InchHeight = 0, Weight = 240, Age = 24, PlayerPositionId = 5, TeamId = 4 },
                new Models.Player { Id = 184, FirstName = "Michael", LastName = "Kidd-Gilchrist", FootHeight = 6, InchHeight = 7, Weight = 232, Age = 23, PlayerPositionId = 3, TeamId = 4 },
                new Models.Player { Id = 185, FirstName = "Jeremy", LastName = "Lamb", FootHeight = 6, InchHeight = 5, Weight = 185, Age = 24, PlayerPositionId = 2, TeamId = 4 },
                new Models.Player { Id = 186, FirstName = "Johnny", LastName = "O'Bryant", FootHeight = 6, InchHeight = 9, Weight = 257, Age = 23, PlayerPositionId = 4, TeamId = 4 },
                new Models.Player { Id = 187, FirstName = "Miles", LastName = "Plumlee", FootHeight = 6, InchHeight = 11, Weight = 249, Age = 28, PlayerPositionId = 5, TeamId = 4 },
                new Models.Player { Id = 188, FirstName = "Brian", LastName = "Roberts", FootHeight = 6, InchHeight = 1, Weight = 173, Age = 31, PlayerPositionId = 1, TeamId = 4 },
                new Models.Player { Id = 189, FirstName = "Ramon", LastName = "Sessions", FootHeight = 6, InchHeight = 3, Weight = 190, Age = 31, PlayerPositionId = 1, TeamId = 4 },
                new Models.Player { Id = 190, FirstName = "Kemba", LastName = "Walker", FootHeight = 6, InchHeight = 1, Weight = 184, Age = 27, PlayerPositionId = 1, TeamId = 4 },
                new Models.Player { Id = 191, FirstName = "Briante", LastName = "Weber", FootHeight = 6, InchHeight = 2, Weight = 165, Age = 24, PlayerPositionId = 1, TeamId = 4 },
                new Models.Player { Id = 192, FirstName = "Marvin", LastName = "Williams", FootHeight = 6, InchHeight = 9, Weight = 237, Age = 30, PlayerPositionId = 4, TeamId = 4 },
                new Models.Player { Id = 193, FirstName = "Christian", LastName = "Wood", FootHeight = 6, InchHeight = 11, Weight = 220, Age = 21, PlayerPositionId = 4, TeamId = 4 },
                new Models.Player { Id = 194, FirstName = "Cody", LastName = "Zeller", FootHeight = 7, InchHeight = 0, Weight = 240, Age = 24, PlayerPositionId = 5, TeamId = 4 },
                new Models.Player { Id = 195, FirstName = "Luke", LastName = "Babbitt", FootHeight = 6, InchHeight = 9, Weight = 225, Age = 27, PlayerPositionId = 3, TeamId = 16 },
                new Models.Player { Id = 196, FirstName = "Goran", LastName = "Dragic", FootHeight = 6, InchHeight = 3, Weight = 190, Age = 31, PlayerPositionId = 1, TeamId = 16 },
                new Models.Player { Id = 197, FirstName = "Wayne", LastName = "Ellington", FootHeight = 6, InchHeight = 4, Weight = 200, Age = 29, PlayerPositionId = 2, TeamId = 16 },
                new Models.Player { Id = 198, FirstName = "Udonis", LastName = "Haslem", FootHeight = 6, InchHeight = 8, Weight = 235, Age = 36, PlayerPositionId = 4, TeamId = 16 },
                new Models.Player { Id = 199, FirstName = "James", LastName = "Johnson", FootHeight = 6, InchHeight = 9, Weight = 238, Age = 30, PlayerPositionId = 4, TeamId = 16 },
                new Models.Player { Id = 200, FirstName = "Tyler", LastName = "Johnson", FootHeight = 6, InchHeight = 4, Weight = 186, Age = 25, PlayerPositionId = 2, TeamId = 16 },
                new Models.Player { Id = 201, FirstName = "Rodney", LastName = "McGruder", FootHeight = 6, InchHeight = 4, Weight = 205, Age = 25, PlayerPositionId = 2, TeamId = 16 },
                new Models.Player { Id = 202, FirstName = "Josh", LastName = "McRoberts", FootHeight = 6, InchHeight = 10, Weight = 240, Age = 30, PlayerPositionId = 4, TeamId = 16 },
                new Models.Player { Id = 203, FirstName = "Willie", LastName = "Reed", FootHeight = 6, InchHeight = 11, Weight = 245, Age = 26, PlayerPositionId = 4, TeamId = 16 },
                new Models.Player { Id = 204, FirstName = "Josh", LastName = "Richardson", FootHeight = 6, InchHeight = 6, Weight = 200, Age = 23, PlayerPositionId = 2, TeamId = 16 },
                new Models.Player { Id = 205, FirstName = "Dion", LastName = "Waiters", FootHeight = 6, InchHeight = 4, Weight = 220, Age = 25, PlayerPositionId = 2, TeamId = 16 },
                new Models.Player { Id = 206, FirstName = "Okaro", LastName = "White", FootHeight = 6, InchHeight = 8, Weight = 204, Age = 24, PlayerPositionId = 4, TeamId = 16 },
                new Models.Player { Id = 207, FirstName = "Hassan", LastName = "Whiteside", FootHeight = 7, InchHeight = 0, Weight = 265, Age = 27, PlayerPositionId = 5, TeamId = 16 },
                new Models.Player { Id = 208, FirstName = "Justise", LastName = "Winslow", FootHeight = 6, InchHeight = 7, Weight = 225, Age = 21, PlayerPositionId = 3, TeamId = 16 },
                new Models.Player { Id = 209, FirstName = "D.J.", LastName = "Augustin", FootHeight = 6, InchHeight = 0, Weight = 183, Age = 29, PlayerPositionId = 1, TeamId = 22 },
                new Models.Player { Id = 210, FirstName = "Bismack", LastName = "Biyombo", FootHeight = 6, InchHeight = 9, Weight = 255, Age = 24, PlayerPositionId = 5, TeamId = 22 },
                new Models.Player { Id = 211, FirstName = "Evan", LastName = "Fournier", FootHeight = 6, InchHeight = 7, Weight = 205, Age = 24, PlayerPositionId = 2, TeamId = 22 },
                new Models.Player { Id = 212, FirstName = "Patricio", LastName = "Garino", FootHeight = 6, InchHeight = 6, Weight = 203, Age =23 , PlayerPositionId = 2, TeamId = 22 },
                new Models.Player { Id = 213, FirstName = "Marcus", LastName = "Georges-Hunt", FootHeight = 6, InchHeight = 6, Weight = 220, Age = 23, PlayerPositionId = 2, TeamId = 22 },
                new Models.Player { Id = 214, FirstName = "Aaron", LastName = "Gordon", FootHeight = 6, InchHeight = 9, Weight = 220, Age = 21, PlayerPositionId = 4, TeamId = 22 },
                new Models.Player { Id = 215, FirstName = "Jeff", LastName = "Green", FootHeight = 6, InchHeight = 9, Weight = 235, Age = 30, PlayerPositionId = 3, TeamId = 22 },
                new Models.Player { Id = 216, FirstName = "Mario", LastName = "Hezonja", FootHeight = 6, InchHeight = 8, Weight = 218, Age = 22, PlayerPositionId = 2, TeamId = 22 },
                new Models.Player { Id = 217, FirstName = "Jodie", LastName = "Meeks", FootHeight = 6, InchHeight = 4, Weight = 210, Age = 29, PlayerPositionId = 2, TeamId = 22 },
                new Models.Player { Id = 218, FirstName = "Elfrid", LastName = "Payton", FootHeight = 6, InchHeight = 4, Weight = 185, Age = 23, PlayerPositionId = 1, TeamId = 22 },
                new Models.Player { Id = 219, FirstName = "Terrence", LastName = "Ross", FootHeight = 6, InchHeight = 7, Weight = 195, Age = 26, PlayerPositionId = 3, TeamId = 22 },
                new Models.Player { Id = 220, FirstName = "Damjan", LastName = "Rudez", FootHeight = 6, InchHeight = 10, Weight = 228, Age = 30, PlayerPositionId = 3, TeamId = 22 },
                new Models.Player { Id = 221, FirstName = "Nikola", LastName = "Vucevic", FootHeight = 7, InchHeight = 0, Weight = 260, Age = 26, PlayerPositionId = 5, TeamId = 22 },
                new Models.Player { Id = 222, FirstName = "C.J.", LastName = "Watson", FootHeight = 6, InchHeight = 2, Weight = 175, Age = 33, PlayerPositionId = 1, TeamId = 22 },
                new Models.Player { Id = 223, FirstName = "Stephen", LastName = "Zimmerman", FootHeight = 7, InchHeight = 0, Weight = 240, Age = 20, PlayerPositionId = 5, TeamId = 22 },
                new Models.Player { Id = 224, FirstName = "Bradley", LastName = "Beal", FootHeight = 6, InchHeight = 5, Weight = 207, Age = 23, PlayerPositionId = 2, TeamId = 30 },
                new Models.Player { Id = 225, FirstName = "Bojan", LastName = "Bogdanovic", FootHeight = 6, InchHeight = 8, Weight = 225, Age = 28, PlayerPositionId = 2, TeamId = 30 },
                new Models.Player { Id = 226, FirstName = "Trey", LastName = "Burke", FootHeight = 6, InchHeight = 1, Weight = 191, Age = 24, PlayerPositionId = 1, TeamId = 30 },
                new Models.Player { Id = 227, FirstName = "Marcin", LastName = "Gortat", FootHeight = 6, InchHeight = 11, Weight = 240, Age = 33, PlayerPositionId = 5, TeamId = 30 },
                new Models.Player { Id = 228, FirstName = "Brandon", LastName = "Jennings", FootHeight = 6, InchHeight = 1, Weight = 170, Age = 27, PlayerPositionId = 1, TeamId = 30 },
                new Models.Player { Id = 229, FirstName = "Ian", LastName = "Mahinmi", FootHeight = 6, InchHeight = 11, Weight = 262, Age = 30, PlayerPositionId = 5, TeamId = 30 },
                new Models.Player { Id = 230, FirstName = "Sheldon", LastName = "McClellan", FootHeight = 6, InchHeight = 6, Weight = 200, Age = 24, PlayerPositionId = 2, TeamId = 30 },
                new Models.Player { Id = 231, FirstName = "Chris", LastName = "McCullough", FootHeight = 6, InchHeight = 9, Weight = 215, Age = 22, PlayerPositionId = 4, TeamId = 30 },
                new Models.Player { Id = 232, FirstName = "Markieff", LastName = "Morris", FootHeight = 6, InchHeight = 10, Weight = 245, Age = 27, PlayerPositionId = 4, TeamId = 30 },
                new Models.Player { Id = 233, FirstName = "Daniel", LastName = "Ochefu", FootHeight = 6, InchHeight = 11, Weight = 245, Age = 23, PlayerPositionId = 4, TeamId = 30 },
                new Models.Player { Id = 234, FirstName = "Kelly", LastName = "Oubre Jr.", FootHeight = 6, InchHeight = 7, Weight = 205, Age = 21, PlayerPositionId = 3, TeamId = 30 },
                new Models.Player { Id = 235, FirstName = "Otto", LastName = "Porter", FootHeight = 6, InchHeight = 8, Weight = 198, Age = 23, PlayerPositionId = 3, TeamId = 30 },
                new Models.Player { Id = 236, FirstName = "Tomas", LastName = "Satoransky", FootHeight = 6, InchHeight = 7, Weight = 210, Age = 25, PlayerPositionId = 2, TeamId = 30 },
                new Models.Player { Id = 237, FirstName = "Jason", LastName = "Smith", FootHeight = 7, InchHeight = 0, Weight = 240, Age = 31, PlayerPositionId = 4, TeamId = 30 },
                new Models.Player { Id = 238, FirstName = "John", LastName = "Wall", FootHeight = 6, InchHeight = 4, Weight = 210, Age = 26, PlayerPositionId = 1, TeamId = 30 }

                );

            context.HistoricalPlayers.AddOrUpdate(m => m.Id,
                 new Models.HistoricalPlayer { Id = 1, FirstName = "Matthew", LastName = "Dellavedova", FootHeight = 6, InchHeight = 4, Weight = 198, Age = 25, PlayerPositionId = 1, HistoricalTeamId = 1 },
                 new Models.HistoricalPlayer { Id = 2, FirstName = "Channing", LastName = "Frye", FootHeight = 6, InchHeight = 11, Weight = 255, Age = 32, PlayerPositionId = 4, HistoricalTeamId = 1 },
                 new Models.HistoricalPlayer { Id = 3, FirstName = "Kyrie", LastName = "Irving", FootHeight = 6, InchHeight = 3, Weight = 193, Age = 24, PlayerPositionId = 1, HistoricalTeamId = 1 },
                 new Models.HistoricalPlayer { Id = 4, FirstName = "LeBron", LastName = "James", FootHeight = 6, InchHeight = 8, Weight = 250, Age = 31, PlayerPositionId = 3, HistoricalTeamId = 1 },
                 new Models.HistoricalPlayer { Id = 5, FirstName = "Richard", LastName = "Jefferson", FootHeight = 6, InchHeight = 7, Weight = 233, Age = 35, PlayerPositionId = 3, HistoricalTeamId = 1 },
                 new Models.HistoricalPlayer { Id = 6, FirstName = "Dahntay", LastName = "Jones", FootHeight = 6, InchHeight = 6, Weight = 225, Age = 35, PlayerPositionId = 2, HistoricalTeamId = 1 },
                 new Models.HistoricalPlayer { Id = 7, FirstName = "James", LastName = "Jones", FootHeight = 6, InchHeight = 8, Weight = 218, Age = 35, PlayerPositionId = 3, HistoricalTeamId = 1 },
                 new Models.HistoricalPlayer { Id = 8, FirstName = "Sasha", LastName = "Kaun", FootHeight = 6, InchHeight = 11, Weight = 250, Age = 30, PlayerPositionId = 5, HistoricalTeamId = 1 },
                 new Models.HistoricalPlayer { Id = 9, FirstName = "Kevin", LastName = "Love", FootHeight = 6, InchHeight = 10, Weight = 251, Age = 27, PlayerPositionId = 4, HistoricalTeamId = 1 },
                 new Models.HistoricalPlayer { Id = 10, FirstName = "Jordan", LastName = "McRae", FootHeight = 6, InchHeight = 5, Weight = 179, Age = 25, PlayerPositionId = 2, HistoricalTeamId = 1 },
                 new Models.HistoricalPlayer { Id = 11, FirstName = "Timofey", LastName = "Mozgov", FootHeight = 7, InchHeight = 1, Weight = 275, Age = 29, PlayerPositionId = 5, HistoricalTeamId = 1 },
                 new Models.HistoricalPlayer { Id = 12, FirstName = "Iman", LastName = "Shumpert", FootHeight = 6, InchHeight = 5, Weight = 220, Age = 25, PlayerPositionId = 2, HistoricalTeamId = 1 },
                 new Models.HistoricalPlayer { Id = 13, FirstName = "J.R.", LastName = "Smith", FootHeight = 6, InchHeight = 6, Weight = 225, Age = 30, PlayerPositionId = 2, HistoricalTeamId = 1 },
                 new Models.HistoricalPlayer { Id = 14, FirstName = "Tristan", LastName = "Thompson", FootHeight = 6, InchHeight = 9, Weight = 238, Age = 25, PlayerPositionId = 4, HistoricalTeamId = 1 },
                 new Models.HistoricalPlayer { Id = 15, FirstName = "Mo", LastName = "Williams", FootHeight = 6, InchHeight = 1, Weight = 198, Age = 33, PlayerPositionId = 1, HistoricalTeamId = 1 },
                 new Models.HistoricalPlayer { Id = 16, FirstName = "Leandro", LastName = "Barbosa", FootHeight = 6, InchHeight = 3, Weight = 194, Age = 32, PlayerPositionId = 2, HistoricalTeamId = 2 },
                 new Models.HistoricalPlayer { Id = 17, FirstName = "Harrison", LastName = "Barnes", FootHeight = 6, InchHeight = 8, Weight = 210, Age = 22, PlayerPositionId = 3, HistoricalTeamId = 2 },
                 new Models.HistoricalPlayer { Id = 18, FirstName = "Andrew", LastName = "Bogut", FootHeight = 7, InchHeight = 0, Weight = 260, Age = 30, PlayerPositionId = 5, HistoricalTeamId = 2 },
                 new Models.HistoricalPlayer { Id = 19, FirstName = "Stephen", LastName = "Curry", FootHeight = 6, InchHeight = 3, Weight = 190, Age = 26, PlayerPositionId = 1, HistoricalTeamId = 2 },
                 new Models.HistoricalPlayer { Id = 20, FirstName = "Festus", LastName = "Ezeli", FootHeight = 6, InchHeight = 11, Weight = 255, Age = 25, PlayerPositionId = 5, HistoricalTeamId = 2 },
                 new Models.HistoricalPlayer { Id = 21, FirstName = "Draymond", LastName = "Green", FootHeight = 6, InchHeight = 7, Weight = 230, Age = 24, PlayerPositionId = 4, HistoricalTeamId = 2 },
                 new Models.HistoricalPlayer { Id = 22, FirstName = "Justin", LastName = "Holiday", FootHeight = 6, InchHeight = 6, Weight = 215, Age = 25, PlayerPositionId = 2, HistoricalTeamId = 2 },
                 new Models.HistoricalPlayer { Id = 23, FirstName = "Andre", LastName = "Iguodala", FootHeight = 6, InchHeight = 6, Weight = 215, Age = 31, PlayerPositionId = 3, HistoricalTeamId = 2 },
                 new Models.HistoricalPlayer { Id = 24, FirstName = "Ognjen", LastName = "Kuzmic", FootHeight = 7, InchHeight = 1, Weight = 251, Age = 24, PlayerPositionId = 5, HistoricalTeamId = 2 },
                 new Models.HistoricalPlayer { Id = 25, FirstName = "David", LastName = "Lee", FootHeight = 6, InchHeight = 9, Weight = 245, Age = 31, PlayerPositionId = 4, HistoricalTeamId = 2 },
                 new Models.HistoricalPlayer { Id = 26, FirstName = "Shaun", LastName = "Livingston", FootHeight = 6, InchHeight = 7, Weight = 192, Age = 29, PlayerPositionId = 1, HistoricalTeamId = 2 },
                 new Models.HistoricalPlayer { Id = 27, FirstName = "James", LastName = "Michael McAdoo", FootHeight = 6, InchHeight = 9, Weight = 230, Age = 22, PlayerPositionId = 4, HistoricalTeamId = 2 },
                 new Models.HistoricalPlayer { Id = 28, FirstName = "Brandon", LastName = "Rush", FootHeight = 6, InchHeight = 6, Weight = 220, Age = 29, PlayerPositionId = 2, HistoricalTeamId = 2 },
                 new Models.HistoricalPlayer { Id = 29, FirstName = "Marreese", LastName = "Speights", FootHeight = 6, InchHeight = 10, Weight = 255, Age = 27, PlayerPositionId = 5, HistoricalTeamId = 2 },
                 new Models.HistoricalPlayer { Id = 30, FirstName = "Klay", LastName = "Thompson", FootHeight = 6, InchHeight = 7, Weight = 215, Age = 24, PlayerPositionId = 2, HistoricalTeamId = 2 },
                 new Models.HistoricalPlayer { Id = 31, FirstName = "Aron", LastName = "Baynes", FootHeight = 6, InchHeight = 10, Weight = 260, Age = 27, PlayerPositionId = 5, HistoricalTeamId =  3 },
                 new Models.HistoricalPlayer { Id = 32, FirstName = "Marco", LastName = "Belinelli", FootHeight = 6, InchHeight = 5, Weight = 210, Age = 28, PlayerPositionId = 2, HistoricalTeamId =  3 },
                 new Models.HistoricalPlayer { Id = 33, FirstName = "Matt", LastName = "Bonner", FootHeight = 6, InchHeight = 10, Weight = 235, Age = 34, PlayerPositionId = 4, HistoricalTeamId =  3 },
                 new Models.HistoricalPlayer { Id = 34, FirstName = "Austin", LastName = "Daye", FootHeight = 6, InchHeight = 11, Weight = 220, Age = 25, PlayerPositionId = 3, HistoricalTeamId =  3 },
                 new Models.HistoricalPlayer { Id = 35, FirstName = "Boris", LastName = "Diaw", FootHeight = 6, InchHeight = 8, Weight = 250, Age = 32, PlayerPositionId = 4, HistoricalTeamId =  3 },
                 new Models.HistoricalPlayer { Id = 36, FirstName = "Tim", LastName = "Duncan", FootHeight = 6, InchHeight = 11, Weight = 250, Age = 37, PlayerPositionId = 4, HistoricalTeamId =  3 },
                 new Models.HistoricalPlayer { Id = 37, FirstName = "Manu", LastName = "Ginobili", FootHeight = 6, InchHeight = 6, Weight = 205, Age = 36, PlayerPositionId = 2, HistoricalTeamId =  3 },
                 new Models.HistoricalPlayer { Id = 38, FirstName = "Danny", LastName = "Green", FootHeight = 6, InchHeight = 6, Weight = 215, Age = 26, PlayerPositionId = 2, HistoricalTeamId =  3 },
                 new Models.HistoricalPlayer { Id = 39, FirstName = "Damion", LastName = "James", FootHeight = 6, InchHeight = 7, Weight = 225, Age = 26, PlayerPositionId = 3, HistoricalTeamId =  3 },
                 new Models.HistoricalPlayer { Id = 40, FirstName = "Cory", LastName = "Joseph", FootHeight = 6, InchHeight = 3, Weight = 190, Age = 22, PlayerPositionId = 1, HistoricalTeamId =  3 },
                 new Models.HistoricalPlayer { Id = 41, FirstName = "Kawhi", LastName = "Leonard", FootHeight = 6, InchHeight = 7, Weight = 230, Age = 22, PlayerPositionId = 3, HistoricalTeamId =  3 },
                 new Models.HistoricalPlayer { Id = 42, FirstName = "Patty", LastName = "Mills", FootHeight = 6, InchHeight = 0, Weight = 185, Age = 25, PlayerPositionId = 1, HistoricalTeamId =  3 },
                 new Models.HistoricalPlayer { Id = 43, FirstName = "Tony", LastName = "Parker", FootHeight = 6, InchHeight = 2, Weight = 185, Age = 31, PlayerPositionId = 1, HistoricalTeamId =  3 },
                 new Models.HistoricalPlayer { Id = 44, FirstName = "Jeff", LastName = "Ayres", FootHeight = 6, InchHeight = 10, Weight = 240, Age = 26, PlayerPositionId = 4, HistoricalTeamId =  3 },
                 new Models.HistoricalPlayer { Id = 45, FirstName = "Tiago", LastName = "Splitter", FootHeight = 6, InchHeight = 11, Weight = 245, Age = 29, PlayerPositionId = 5, HistoricalTeamId =  3 },
                 new Models.HistoricalPlayer { Id = 46, FirstName = "Ray", LastName = "Allen", FootHeight = 6, InchHeight = 5, Weight = 205, Age = 37, PlayerPositionId = 2, HistoricalTeamId =  4 },
                 new Models.HistoricalPlayer { Id = 47, FirstName = "Chris", LastName = "Anderson", FootHeight = 6, InchHeight = 10, Weight = 245, Age = 34, PlayerPositionId = 5, HistoricalTeamId =  4 },
                 new Models.HistoricalPlayer { Id = 48, FirstName = "Joel", LastName = "Anthony", FootHeight = 6, InchHeight = 9, Weight = 245, Age = 30, PlayerPositionId = 5, HistoricalTeamId =  4 },
                 new Models.HistoricalPlayer { Id = 49, FirstName = "Shane", LastName = "Battier", FootHeight = 6, InchHeight = 8, Weight = 220, Age = 34, PlayerPositionId = 3, HistoricalTeamId =  4 },
                 new Models.HistoricalPlayer { Id = 50, FirstName = "Chris", LastName = "Bosh", FootHeight = 6, InchHeight = 11, Weight = 235, Age = 29, PlayerPositionId = 4, HistoricalTeamId =  4 },
                 new Models.HistoricalPlayer { Id = 51, FirstName = "Mario", LastName = "Chalmers", FootHeight = 6, InchHeight = 2, Weight = 190, Age = 26, PlayerPositionId = 1, HistoricalTeamId =  4 },
                 new Models.HistoricalPlayer { Id = 52, FirstName = "Norris", LastName = "Cole", FootHeight = 6, InchHeight = 2, Weight = 175, Age = 24, PlayerPositionId = 1, HistoricalTeamId =  4 },
                 new Models.HistoricalPlayer { Id = 53, FirstName = "Udonis", LastName = "Haslem", FootHeight = 6, InchHeight = 8, Weight = 235, Age = 32, PlayerPositionId = 4, HistoricalTeamId =  4 },
                 new Models.HistoricalPlayer { Id = 54, FirstName = "Juwan", LastName = "Howard", FootHeight = 6, InchHeight = 9, Weight = 240, Age = 40, PlayerPositionId = 4, HistoricalTeamId =  4 },
                 new Models.HistoricalPlayer { Id = 55, FirstName = "LeBron", LastName = "James", FootHeight = 6, InchHeight = 8, Weight = 250, Age = 28, PlayerPositionId = 3, HistoricalTeamId =  4 },
                 new Models.HistoricalPlayer { Id = 56, FirstName = "James", LastName = "Jones", FootHeight = 6, InchHeight = 8, Weight = 218, Age = 32, PlayerPositionId = 3, HistoricalTeamId =  4 },
                 new Models.HistoricalPlayer { Id = 57, FirstName = "Rashard", LastName = "Lewis", FootHeight = 6, InchHeight = 10, Weight = 235, Age = 33, PlayerPositionId = 3, HistoricalTeamId =  4 },
                 new Models.HistoricalPlayer { Id = 58, FirstName = "Mike", LastName = "Miller", FootHeight = 6, InchHeight = 8, Weight = 218, Age = 33, PlayerPositionId = 2, HistoricalTeamId =  4 },
                 new Models.HistoricalPlayer { Id = 59, FirstName = "Jarvis", LastName = "Varnado", FootHeight = 6, InchHeight = 9, Weight = 230, Age = 25, PlayerPositionId = 4, HistoricalTeamId =  4 },
                 new Models.HistoricalPlayer { Id = 60, FirstName = "Dwyane", LastName = "Wade", FootHeight = 6, InchHeight = 4, Weight = 220, Age = 31, PlayerPositionId = 2, HistoricalTeamId =  4 }
                );

           

        }
    }
}
